### ISSUE TITLE
Ask Referee about Relegating 1+2 Dimensions to the Appendix

### ISSUE THREAD

**Issue by evanberkowitz** [ckoerber/luescher-nd#40]
In terms of flow it could help to tell a tighter story if we put 1+2D in the appendix.  But that's a major restructuring, let's check with the referee if s/he thinks that would be a substantial improvement.

**Comment by ckoerber** [comment]
Ok, pushed the first draft for our reply. Feel free to adjust the message.

**Comment by ckoerber** [comment]
Reply of editor:

> We suggest that you revise your manuscript and respond to the referee as best you can, interpreting their intention to the best of your ability. 

So no feedback until we send in a *complete* reply.
